DEBUG:root:Starting keylogger
ERROR:pynput.keyboard.Listener:Unhandled exception in listener callback
Traceback (most recent call last):
  File "/home/cybermemo/Documentos/Python/.venv/lib64/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/home/cybermemo/Documentos/Python/.venv/lib64/python3.13/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
DEBUG:root:Keylogger stopped
DEBUG:root:Starting keylogger
ERROR:pynput.keyboard.Listener:Unhandled exception in listener callback
Traceback (most recent call last):
  File "/home/cybermemo/Documentos/Python/.venv/lib64/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/home/cybermemo/Documentos/Python/.venv/lib64/python3.13/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
DEBUG:root:Keylogger stopped
